export const ApiErrorCodes = {
  ERROR_GENERIC_TIME_OUT: 'ERROR_GENERIC_TIME_OUT',
  ERROR_NO_TRADING_ACCOUNT_ENABLED: 'ERROR_NO_TRADING_ACCOUNT_ENABLED',
  ERROR_TAKE_UP_FAILURE: 'ERROR_TAKE_UP_FAILURE',
  ERROR_MARKET_DATA_UPDATE_FAILURE: 'ERROR_MARKET_DATA_UPDATE_FAILURE',
  ERROR_INACTIVITY_DETECTED: 'ERROR_INACTIVITY_DETECTED',
  ERROR_SOMETHING_WENT_WRONG: 'ERROR_SOMETHING_WENT_WRONG',
  ERROR_AUTHORIZATION: 'ERROR_AUTHORIZATION',
};
